
import type { Project, Testimonial, ProjectStatus } from '@/types';

export const placeholderProjects: Project[] = [
  {
    id: '1',
    address: '55 Hillside Ave',
    status: 'SOLD',
    thumbnailUrl: '/images/projects/55 Hillside/1.jpg',
    description: 'Beautiful property at 55 Hillside Ave, now sold. This property featured modern designs and spacious living areas.',
    images: [
      '/images/projects/55 Hillside/2.jpg',
      '/images/projects/55 Hillside/3.jpg',
      '/images/projects/55 Hillside/4.jpg',
      '/images/projects/55 Hillside/5.jpg',
      '/images/projects/55 Hillside/6.jpg',
    ],
    category: 'Residential',
  },
  {
    id: '2',
    address: '280 W Mt Pleasant Ave',
    status: 'SOLD',
    thumbnailUrl: '/images/projects/280 W Mt Pleasant Ave/1.jpg',
    description: 'Charming residence at 280 W Mt Pleasant Ave. Sold to a happy new owner, this home offers comfort and style.',
    images: [
      '/images/projects/280 W Mt Pleasant Ave/2.jpg',
      '/images/projects/280 W Mt Pleasant Ave/3.jpg',
      '/images/projects/280 W Mt Pleasant Ave/4.jpg',
      '/images/projects/280 W Mt Pleasant Ave/5.jpg',
      '/images/projects/280 W Mt Pleasant Ave/6.jpg',
      '/images/projects/280 W Mt Pleasant Ave/7.jpg',
      '/images/projects/280 W Mt Pleasant Ave/8.jpg',
      '/images/projects/280 W Mt Pleasant Ave/9.jpg',
      '/images/projects/280 W Mt Pleasant Ave/10.jpg',
      '/images/projects/280 W Mt Pleasant Ave/11.jpg',
      '/images/projects/280 W Mt Pleasant Ave/12.jpg',
      '/images/projects/280 W Mt Pleasant Ave/13.jpg',
      '/images/projects/280 W Mt Pleasant Ave/14.jpg',
      '/images/projects/280 W Mt Pleasant Ave/15.jpg',
    ],
    category: 'Residential',
  },
  {
    id: '3',
    address: '25 Sterling Drive',
    status: 'SOLD',
    thumbnailUrl: 'https://picsum.photos/seed/sterling/600/400',
    description: 'Located at 25 Sterling Drive, this exquisite house found its new owners. It boasts premium finishes and a prime location.',
    images: [
      'https://picsum.photos/seed/sterling_detail1/1200/800',
      'https://picsum.photos/seed/sterling_detail2/1200/800',
    ],
    category: 'Residential',
  },
  {
    id: '4',
    address: '11 Country Club Road',
    status: 'IN MARKET',
    thumbnailUrl: '/images/projects/11 Country Club Road/2.jpg',
    description: 'An exceptional opportunity at 11 Country Club Road. Currently in the market, this property is perfect for discerning buyers seeking luxury and exclusivity.',
    images: [
      '/images/projects/11 Country Club Road/1.jpg',
      '/images/projects/11 Country Club Road/3.jpg',
      '/images/projects/11 Country Club Road/4.jpg',
      '/images/projects/11 Country Club Road/5.jpg',
      '/images/projects/11 Country Club Road/6.jpg',
      '/images/projects/11 Country Club Road/7.jpg',
      '/images/projects/11 Country Club Road/8.jpg',
      '/images/projects/11 Country Club Road/9.jpg',
      '/images/projects/11 Country Club Road/10.jpg',
      '/images/projects/11 Country Club Road/11.jpg',
      '/images/projects/11 Country Club Road/12.jpg',
      '/images/projects/11 Country Club Road/13.jpg',
      '/images/projects/11 Country Club Road/14.jpg',
      '/images/projects/11 Country Club Road/15.jpg',
      '/images/projects/11 Country Club Road/16.jpg',
      '/images/projects/11 Country Club Road/17.jpg',
      '/images/projects/11 Country Club Road/18.jpg',
      '/images/projects/11 Country Club Road/19.jpg',
      '/images/projects/11 Country Club Road/20.jpg',
      '/images/projects/11 Country Club Road/21.jpg',
      '/images/projects/11 Country Club Road/22.jpg',
      '/images/projects/11 Country Club Road/23.jpg',
      '/images/projects/11 Country Club Road/24.jpg',
      '/images/projects/11 Country Club Road/25.jpg',
      '/images/projects/11 Country Club Road/26.jpg',
      '/images/projects/11 Country Club Road/27.jpg',
      '/images/projects/11 Country Club Road/28.jpg',
      '/images/projects/11 Country Club Road/29.jpg', 
      '/images/projects/11 Country Club Road/30.jpg',
    ],
    category: 'Residential',
  },
  {
    id: '5',
    address: '27 Mounthaven Dr',
    status: 'UNDER CONSTRUCTION',
    thumbnailUrl: 'https://picsum.photos/seed/mounthaven/600/400',
    description: 'Exciting new development at 27 Mounthaven Dr. Currently under construction, this future home will feature contemporary architecture and smart home technology.',
    images: ['https://picsum.photos/seed/mounthaven_detail1/1200/800'],
    category: 'Residential',
  },
  {
    id: '6',
    address: '54 Melrose Dr',
    status: 'SOLD (Under Construction)',
    thumbnailUrl: 'https://picsum.photos/seed/melrose/600/400',
    description: '54 Melrose Dr is sold and currently under construction. The new owners are eagerly awaiting their custom-built dream home.',
    images: [
      'https://picsum.photos/seed/melrose_detail1/1200/800',
      'https://picsum.photos/seed/melrose_detail2/1200/800',
    ],
    category: 'Residential',
  },
  {
    id: '7',
    address: '73 W Cedar St',
    status: 'SOLD (Under Construction)',
    thumbnailUrl: 'https://picsum.photos/seed/cedar/600/400',
    description: 'Another successful sale at 73 W Cedar St, with construction underway. This property promises to be a stunning addition to the neighborhood.',
    images: ['https://picsum.photos/seed/cedar_detail1/1200/800'],
    category: 'Residential',
  },
  {
    id: '8',
    address: '11 Elmwood CT',
    status: 'PLAN REVIEW',
    thumbnailUrl: 'https://picsum.photos/seed/elmwood/600/400',
    description: 'Upcoming project at 11 Elmwood CT, currently in plan review. We are excited about the innovative design and features planned for this property.',
    images: ['https://picsum.photos/seed/elmwood_detail1/1200/800'],
    category: 'Residential',
  },
];

export const placeholderTestimonials: Testimonial[] = [
  {
    id: '1',
    quote: "EstateView transformed our vision into a reality. Their attention to detail and commitment to quality is outstanding. We couldn't be happier with our new headquarters.",
    author: 'Sarah Chen',
    company: 'CEO, Innovatech Solutions',
    avatarUrl: 'https://picsum.photos/seed/avatar1/100/100',
  },
  {
    id: '2',
    quote: 'Working with EstateView was a seamless experience. Their professionalism and expertise made the entire construction process smooth and efficient. Our dream home is perfect!',
    author: 'John & Emily Carter',
    company: 'Homeowners',
    avatarUrl: 'https://picsum.photos/seed/avatar2/100/100',
  },
  {
    id: '3',
    quote: "The team at EstateView is exceptional. They delivered our project on time and within budget, exceeding all our expectations. Highly recommended for any large-scale development.",
    author: 'David Lee',
    company: 'Director, Urban Developers Inc.',
    avatarUrl: 'https://picsum.photos/seed/avatar3/100/100',
  },
];

export const heroCarouselImages = [
  { id: 'hero1', src: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c', alt: 'Luxurious modern home exterior', title: 'Building the Future', subtitle: 'Exquisite Properties, Expertly Crafted' , dataAiHint: 'modern luxury home' },
  { id: 'hero2', src: '/images/carousel/john-fornander-Id7u0EkTjBE-unsplash.jpg', alt: 'Elegant modern house facade', title: 'Innovative Design', subtitle: 'Where Vision Meets Precision', dataAiHint: 'modern luxury home' },
  { id: 'hero3', src: '/images/carousel/3.jpg', alt: 'Ongoing construction site with cranes', title: 'Sustainable Solutions', subtitle: 'Constructing a Greener Tomorrow', dataAiHint: 'construction site' },
  { id: 'hero4', src: '/images/carousel/4.jpg', alt: 'Construction workers at a building site', title: 'Dream Homes Delivered', subtitle: 'Quality Craftsmanship, Lasting Value', dataAiHint: 'construction site' },
  { id: 'hero5', src: '/images/carousel/5.jpg', alt: 'Team of builders and engineers at a project site', title: 'Architectural Excellence', subtitle: 'Shaping Skylines, Inspiring Lives', dataAiHint: 'builder team' },
  { id: 'hero6', src: '/images/carousel/6.jpg', alt: 'Beautifully finished modern interior room', title: 'Premium Developments', subtitle: 'Your Vision, Our Expertise', dataAiHint: 'interior design' },
];

